import type { Metadata } from 'next'
import { Geist, Geist_Mono, Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { TooltipProvider } from '@/components/ui/tooltip'
import { SessionProvider } from 'next-auth/react'
import { OverlayProvider } from '@/hooks/use-overlay'
import { Toaster } from '@/components/ui/sonner'

import { auth } from '@/auth'
//
const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <OverlayProvider>
          <TooltipProvider>
            <SessionProvider
              session={session}
              refetchInterval={0}
              refetchOnWindowFocus={false}
            >
              {children}
            </SessionProvider>
          </TooltipProvider>
          <Toaster position="top-right" />
        </OverlayProvider>
      </body>
    </html>
  )
}
