import type { Metadata } from 'next'
import { Geist, Geist_Mono, Itim } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { TooltipProvider } from '@/components/ui/tooltip'
import { SessionProvider } from 'next-auth/react'
import { OverlayProvider } from '@/hooks/use-overlay'
import TanstackQueryProvider from '@/hooks/tanstack-query'
import { Toaster } from '@/components/ui/sonner'

import { auth } from '@/auth'
//
const itim = Itim({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-sans',
})

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        itim.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <SessionProvider
          session={session}
          refetchInterval={0}
          refetchOnWindowFocus={false}
        >
          <TanstackQueryProvider>
            <OverlayProvider>
              <TooltipProvider>{children}</TooltipProvider>
              <Toaster position="top-right" />
            </OverlayProvider>
          </TanstackQueryProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
